version: "3"
services:
  nginx:
    image: springboot-nginx:0.1  
    volumes:
      - certs:/etc/letsencrypt
      - certs-data:/data/letsencrypt
    ports:
      - 80:80
      - 443:443
    depends_on:
      - docker-springboot
  docker-springboot:
    build: .
    expose:
      - 8080
