var data = {
    input: '# Project Title\n'
    + '---\n'
    + 'One Paragraph of project description goes here\n'
    + '## Getting Started:smile:\n'
    + '---\n'
    + 'These instructions will get you a copy of the project up and running on your local machine for development and testing purposes. See deployment for notes on how to deploy the project on a live system.\n'
    + '## Prerequisites\n'
    + 'What things you need to install the software and how to install them\n'
    + '```\n'
    + 'Give examples\n'
    + '```\n'
    + '## Installing\n'
    + 'A step by step series of examples that tell you how to get a development env running\n'
    + 'Say what the step will be\n'
    + '```\n'
    + 'Give the example\n'
    + '```\n'
    + 'And repeat\n'
    + '```\n'
    + 'until finished\n'
    + '```\n'
    + 'End with an example of getting some data out of the system or using it for a little demo\n'
    + '## Running the tests\n'
    + '---\n'
    + 'Explain how to run the automated tests for this system\n'
    + '### Break down into end to end tests\n'
    + 'Explain what these tests test and why\n'
    + '```\n'
    +'Give an example\n'
    +'```\n'
    +'### And coding style tests\n'
    +'Explain what these tests test and why\n'
    +'```\n'
    +'Give an example\n'
    +'```\n'
    +'## Deployment\n'
    +'---\n'
    +'Add additional notes about how to deploy this on a live system\n'
    
    +'## Built With\n'
    +'---\n'
    +'- Dropwizard - The web framework used\n'
    +'- Maven - Dependency Management\n'
    +'- ROME - Used to generate RSS Feeds\n'
    +'## Contributing\n'
    +'---\n'
    +'Please read CONTRIBUTING.md for details on our code of conduct, and the process for submitting pull requests to us.\n'
    +'## Versioning\n'
    +'---\n'
    +'We use SemVer for versioning. For the versions available, see the tags on this repository.\n'
    +'## Authors\n'
    +'---\n'
    +'- Billie Thompson - Initial work - PurpleBooth\n'
    +'See also the list of contributors who participated in this project.\n'
    + '## License\n'
    + '---\n'
    + 'This project is licensed under the MIT License - see the LICENSE.md file for details\n'
    +'## Acknowledgments\n'
    +'---\n'
    +'- Hat tip to anyone whose code was used\n'
    +'- Inspiration\n'
    +'- etc\n'
    +'---\n'
    +'<자료 출처: [Readme](https://gist.github.com/PurpleBooth/109311bb0361f32d87a2#file-readme-template-md, "Readme") >\n'
};

export default data;