var data = {
    input: '# :rocket: Project Title\n'
    + 'One Paragraph of project description goes here\n'
    + '## :sparkles: Started\n'
    + 'These instructions will get you a copy of the project up and running on your local machine for development and testing purposes. See deployment for notes on how to deploy the project on a live system.:smile:\n'
    + '## :scream: Introduce\n'
    + '@[video](https://www.youtube.com/watch?v=wcsVjmHrUQg)\n'
    + '## Prerequisites\n'
    + 'What things you need to install the software and how to install them\n'
    + '```\n'
    + "// The package.json is not required to run README-MD-GENERATOR\n"
    + "{\n"
    + '  "name": "readme-md-generator"\n'
    + '  "version": "0.1.3"\n'
    + '  "description": "CLI that generates beautiful README.md files."\n'
    + '  "author": "Franck Abgrall"\n'
    + '  "license": "MIT"\n'
    + '  "homepage": "https://github.com/kefranabg/readme-md-generator#readme"\n'
    + '  "repository": {\n'
    + '  "type": "git"\n'
    + '  "url": "git+https://github.com/kefranabg/readme-md-generator.git"\n'
    + '}\n'
    + '"bugs": {\n'
    +   '"url": "https://github.com/kefranabg/readme-md-generator/issues"\n'
    + '}\n'
    + '"engines": {\n'
    + '  "npm": ">=5.5.0"\n'
    + '  "node": ">=9.3.0"\n'
    + ' }\n'
    + '}\n'
    + '```\n'
    + '## Installing\n'
    + ':one: A step by step series of examples that tell you how to get a development env running\n'
    + 'Say what the step will be\n'
    + '```\n'
    + 'Give the example\n'
    + '```\n'
    + ':two: And repeat\n'
    + '```\n'
    + 'until finished\n'
    + '```\n'
    + ':three: End with an example of getting some data out of the system or using it for a little demo\n'
    + '## Running the tests\n'
    + 'Explain how to run the automated tests for this system\n'
    + '### Break down into end to end tests\n'
    + 'Explain what these tests test and why\n'
    + '```\n'
    +'Give an example\n'
    +'```\n'
    +'### And coding style tests\n'
    +'Explain what these tests test and why\n'
    +'```\n'
    +'Give an example\n'
    +'```\n'
    +'## Deployment\n'
    +'Add additional notes about how to deploy this on a live system\n'
    +'## Built With\n'
    +'- :ng_man: Dropwizard - The web framework used\n'
    +'- :ng_woman: Maven - Dependency Management\n'
    +'- :tipping_hand_man: ROME - Used to generate RSS Feeds\n\n\n\n'
    +'## Contributing\n'
    +'Please read CONTRIBUTING.md for details on our code of conduct, and the process for submitting pull requests to us.\n'
    +'## :clock1030: Versioning\n'
    +'We use SemVer for versioning. For the versions available, see the tags on this repository.\n'
    +'## :shrug: Authors\n'
    +'- Billie Thompson - Initial work - PurpleBooth\n'
    +'See also the list of contributors who participated in this project.\n'
    + '## :lock: License\n'
    + 'This project is licensed under the MIT License - see the LICENSE.md file for details\n\n\n\n'
    +'## Acknowledgments\n'
    +'- Hat tip to anyone whose code was used\n'
    +'- Inspiration\n'
    +'- etc\n'
    +'---\n'
    +'<자료 출처: [Readme](https://gist.github.com/PurpleBooth/109311bb0361f32d87a2#file-readme-template-md, "Readme") >\n'
};

export default data;